using System.Collections.Generic;
using System.Linq;

namespace SimulatorSA.Bacnet.Mapping;

public static class BacnetObjectCatalog
{
    public static IReadOnlyList<BacnetPointMap> All { get; } =
        new List<BacnetPointMap>
        {
            new BacnetPointMap(
                BacnetObjectKind.AnalogInput,
                1,
                "room.temperature",
                "Room Temperature",
                "Current simulated indoor room temperature"),

            new BacnetPointMap(
                BacnetObjectKind.AnalogInput,
                2,
                "room.outdoor_temperature",
                "Outdoor Temperature",
                "Current outdoor temperature used by the simulation"),

            new BacnetPointMap(
                BacnetObjectKind.AnalogInput,
                3,
                "heating.power",
                "Heating Power",
                "Current heating power delivered to the room"),

            new BacnetPointMap(
                BacnetObjectKind.AnalogInput,
                4,
                "room.error",
                "Temperature Error",
                "Difference between setpoint and room temperature"),

            new BacnetPointMap(
                BacnetObjectKind.AnalogOutput,
                1,
                "controller.output",
                "Heating Command",
                "Current actuator command generated by the controller"),

            new BacnetPointMap(
                BacnetObjectKind.AnalogValue,
                1,
                "room.setpoint",
                "Room Setpoint",
                "Temperature setpoint used by the controller",
                isWritable: true)
        };

    public static BacnetPointMap? Find(BacnetObjectKind objectType, uint instance)
    {
        return All.FirstOrDefault(x =>
            x.ObjectType == objectType &&
            x.Instance == instance);
    }
}